name: subrepo-pull-into-main
on:
  push:
    branches: [dist]

permissions:
  contents: write
  pull-requests: write

jobs:
  pull-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Install git-subrepo
        run: |
          git clone https://github.com/ingydotnet/git-subrepo ~/.git-subrepo

      - name: Set up Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Generate branch name
        id: generate-branch-name
        run: |
          TIMESTAMP=$(date +%Y_%m_%d-%H_%M_%S_%Z)
          BRANCH_NAME="chore/update-dist-${TIMESTAMP}"
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Using branch name: $BRANCH_NAME"

      - name: Update dist/ from origin:dist
        run: |
          set -e
          git switch -c "${{ steps.generate-branch-name.outputs.branch-name }}"
          source ~/.git-subrepo/.rc
          git subrepo pull dist --branch dist --remote "$(git remote get-url origin)" --update --verbose
          git push -u origin HEAD

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head "${{ steps.generate-branch-name.outputs.branch-name }}" \
            --title "chore(dist): pull latest upstream dist into main" \
            --body "Automated subrepo pull of origin:dist into ./dist"