name: subrepo-push-dist
on:
  push:
    branches: [main]
    paths:
      - "dist/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-subrepo
        run: |
          git clone https://github.com/ingydotnet/git-subrepo ~/.git-subrepo
          source ~/.git-subrepo/.rc
          git subrepo --version

      - name: Set up Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Configure Git credentials
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Pull (to integrate) then push
        run: |
          set -e
          source ~/.git-subrepo/.rc
          git subrepo pull dist -b dist -r "$(git remote get-url origin)" -u || true
          git subrepo push dist -b dist -r "$(git remote get-url origin)"